
spring:
  datasource:
    url: jdbc:mysql://xit.nwu.edu.cn:3306/tutor_select?serverTimezong=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wwwsql240


  # 配置上传文件大小
  servlet:
    multipart:
      max-file-size: 500MB      # 最大文件限制
      max-request-size: 500MB   # 单次请求最大文件限制

# mybatis 信息
mybatis:
  # 加载 Mybatis 映射文件
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # 配置 pojo 别名
  type-aliases-package: com.nwu.entities
  # 配置下划线自动转驼峰命名
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081
logging:
  level:
    com.nwu.mapper: debug

#上传文件路径
FilePath: D://RARZIP/uploadFile/
#图片保存路径
ImagePath: D://RARZIP/image/
#pdf生成路径
PdfPath: D:\\RARZIP\\PDF\\
#配置方言
pagehelper:
  helper-dialect: mysql

# 统一认证
union:
  # 统一认证服务接口
  casURL: http://authserver.nwu.edu.cn/authserver
  # 部署统一认证应用接口
  appURL: http://10.8.47.148:8081/

